services:
  fluffy-strapi:
    container_name: fluffy-strapi
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST:-fluffy-strapi-db}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PRIVATE_ENDPOINT: ${MINIO_PRIVATE_ENDPOINT}
      MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT}
      MINIO_REGION: ${MINIO_REGION}
      MINIO_BUCKET: ${MINIO_BUCKET}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package.json:/opt/app/package.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - fluffy-strapi-db
    command: bash -c "yarn restore && yarn dev"
    extra_hosts:
      - "host.docker.internal:192.168.1.207"

  fluffy-strapi-db:
    container_name: fluffy-strapi-db
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres_db_strapi:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - strapi

networks:
  strapi:
    driver: bridge
